/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-09-01 02:36:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Dtos.*;
import Utils.*;

public final class _02Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	/* 문제 : 유효성 검증함수 만들기 */
	public boolean isValid(MemberDto dto){
		//1) 각 항목 not null (message : '-' 를 입력하세요 - System.out 으로 출력후 false)
		// 각 항목이 비어있을 경우 항목에 해당하는 '항목명'을 입력하세요 라는 문구 출력 -> false 값 반환
		// 모든 항목이 비어있지 않고 모든 조건 만족 시 true 값 반환하여 다음으로 넘어감
		if(dto.getUserid().isEmpty()){
			System.out.println("Userid를 입력하세요.");
			return false;
		}
		if(dto.getPassword().isEmpty()){
			System.out.println("password를 입력하세요.");
			return false;
		}
		if(dto.getUsername().isEmpty()){
			System.out.println("Username을 입력하세요.");
			return false;
		}
		if(dto.getZipcode().isEmpty()){
			System.out.println("Zipcode를 입력하세요.");
			return false;
		}
		if(dto.getAddr1().isEmpty()){
			System.out.println("Addr1을 입력하세요.");
			return false;
		}
		if(dto.getAddr2().isEmpty()){
			System.out.println("Addr2를 입력하세요.");
			return false;
		}
		if(dto.getPhone1().isEmpty()){
			System.out.println("Phone1을 입력하세요.");
			return false;
		}
		if(dto.getPhone2().isEmpty()){
			System.out.println("Phone2를 입력하세요.");
			return false;
		}
		if(dto.getPhone3().isEmpty()){
			System.out.println("Phone3를 입력하세요.");
			return false;
		}
		if(dto.getTel1().isEmpty()){
			System.out.println("Tel1을 입력하세요.");
			return false;
		}
		if(dto.getTel2().isEmpty()){
			System.out.println("Tel2를 입력하세요.");
			return false;
		}
		if(dto.getTel3().isEmpty()){
			System.out.println("Tel3를 입력하세요.");
			return false;
		}
		if(dto.getEmail().isEmpty()){
			System.out.println("Email을 입력하세요.");
			return false;
		}
		if(dto.getYear().isEmpty()){
			System.out.println("year를 입력하세요.");
			return false;
		}
		if(dto.getMonth().isEmpty()){
			System.out.println("Month를 입력하세요.");
			return false;
		}
		if(dto.getDay().isEmpty()){
			System.out.println("Day를 입력하세요.");
			return false;
		}
		
		//2) userid 길이 5자 이하(message : Userid는 5자 이상 입력하셔야 합니다.- System.out 으로 출력후 false)
		if(dto.getUserid().length()<=5){
			System.out.println("Userid를 5자 이상 입력하서야 합니다.");
			return false;
		}
		//3) 패스워드 유효성 검증(regex : ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{8,20}$ )
		//- System.out 으로 출력후 false
		if(dto.getPassword().matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[\\W_]).{8,20}$ ")) {
			System.out.println("소문자, 대문자, 숫자, 특수문자 포함, 8자 이상 20자 이내로 입력해주세요");
			return false;
		}
		
		return true;
	}	

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Dtos");
    _jspx_imports_packages.add("Utils");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 문제 : 선언문(적절한 클래스 import 하기) -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

	/* 문제 : 문자셋 설정 */
	request.setCharacterEncoding("UTF-8");
	response.setContentType("text/html; charset=UTF-8");

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  01 문제 : 파라미터 받기 (액션태그 jsp:useBean , jsp:setProperty 로 MemberDto 단위로 받기-->\r\n");
      out.write("\r\n");
      Dtos.MemberDto dto = null;
      dto = (Dtos.MemberDto) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new Dtos.MemberDto();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("dto"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	try{
		//-----------------------------
		//02 유효성 검증	
		//-----------------------------
		if(!isValid(dto)){
			//유효하지 않는경우에 -> 01Join.html 로 Forwarding
			request.getRequestDispatcher("./01Join.html").forward(request, response);
			return;
		}
		//-----------------------------
		//03 서비스 처리(회원가입->DB 저장)
		//-----------------------------
		//03-01 db연결
		DbUtils.conn();
		
		//03-02 Tx 시작
		DbUtils.TxStart();
		
		//03-03 동일 계정유무확인
		MemberDto exist = DbUtils.selectMember(dto.getUserid());
		// DbUtils 클래스의 selectMember 메서드를 호출해 전달받은 userid로 회원 정보를 조회하고 exist 변수에 저장
		if(exist != null) {
			System.out.println("이미 존재하는 계정입니다.");
			request.getRequestDispatcher("./01Join.html").forward(request, response);
			return;
		}
		// 조회된 회원정보(exist)가 null 값이 아니라면, 즉 동일한 아이디가 이미 존재한다면
		// "이미 존재하는 계정입니다."라는 메시지 출력 후 01Join.html 페이지로 포워딩
		// 이후 코드 실행을 막기 위해 리턴
		
		
		//03-04 계정정보 저장
		int result = DbUtils.insertMember(dto);
		// DbUtils 클래스의 insertMember 메서드를 호출해 DB에 저장하고 결과 값 반환
		if(result <=0) {
			System.out.println("회원가입에 실패했습니다.");
			request.getRequestDispatcher("./01Join.html").forward(request, response);
			return;
		}
		// insertMember 실행 결과가 0 이하라면(저장 실패)
		// "회원가입에 실패했습니다." 라는 메시지 출력 후 01Join.html 페이지로 포워딩
		// 이후 코드 실행을 막기 위해 리턴
		
		//03-05 Tx 종료
		DbUtils.TxEnd();
		//03-06 연결해제
		DbUtils.disConn();
			
		
		//-----------------------------
		//04 로그인 페이지로 이동
		//-----------------------------
		//04-01 "회원가입을 완료했습니다" 를 system.out 으로 출력
		System.out.println("회원가입을 완료했습니다.");
		response.sendRedirect("./03Login.jsp");
	}
		//04-02 Login.jsp 로 리다이렉트
		catch(Exception e){
		//"문제 발생 ROLLBACK" system.out 출력
		System.out.println("문제 발생 ROLLBACK");
		//TX ROLLBACK 처리
		DbUtils.RollBack();
	}
		

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
